# Generated by Django 3.1.7 on 2021-03-16 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contain', to='Services.services')),
            ],
        ),
    ]
