# Generated by Django 3.1.7 on 2021-03-17 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_person_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('request_place', models.CharField(max_length=40)),
                ('idd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Services.service_details')),
                ('idperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Services.person')),
            ],
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
