# Generated by Django 3.1.7 on 2021-03-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_auto_20210317_0936'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requests',
            new_name='Request',
        ),
    ]
