# Generated by Django 3.1.7 on 2021-03-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_auto_20210317_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_namber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
