# Generated by Django 3.1.7 on 2021-03-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0007_auto_20210317_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='fhasbend',
            field=models.CharField(max_length=30, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=20, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='person',
            name='hasbend',
            field=models.CharField(max_length=30, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.SmallIntegerField(null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=100, null='True'),
        ),
        migrations.AlterField(
            model_name='person',
            name='place_birth',
            field=models.CharField(max_length=30, null='True'),
        ),
    ]
