# Generated by Django 3.1.7 on 2021-03-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0008_auto_20210321_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='assistance',
            field=models.CharField(max_length=40, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='person',
            name='card_number',
            field=models.IntegerField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='person',
            name='count_child',
            field=models.IntegerField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='person',
            name='percentage_health',
            field=models.IntegerField(null='True'),
            preserve_default='True',
        ),
    ]
