# Generated by Django 3.1.7 on 2021-04-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0009_auto_20210321_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='amount_money',
            field=models.DecimalField(decimal_places=2, max_digits=6, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(null='True', upload_to='photos/%Y/%M/'),
            preserve_default='True',
        ),
    ]
