# Generated by Django 3.1.7 on 2021-04-27 13:56

import Services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0010_auto_20210402_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Birthdays',
            field=models.DateField(default='1-1-2000'),
        ),
        migrations.RemoveField(
            model_name='person',
            name='assistance',
        ),
        migrations.AddField(
            model_name='person',
            name='assistance',
            field=models.ManyToManyField(through='Services.Request', to='Services.Service_details'),
        ),
        migrations.AlterField(
            model_name='person',
            name='card_number',
            field=models.PositiveIntegerField(null='True'),
        ),
        migrations.AlterField(
            model_name='person',
            name='count_child',
            field=models.PositiveIntegerField(null='True'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_namber',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='percentage_health',
            field=models.PositiveIntegerField(null='True'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.FileField(null='True', upload_to=Services.models.Person.user_directory_path),
        ),
    ]
