# Generated by Django 3.1.7 on 2021-04-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0012_auto_20210427_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='Birthdays',
        ),
    ]
