# Generated by Django 3.1.7 on 2021-04-27 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0013_remove_person_birthdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='berthday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
