# Generated by Django 3.1.7 on 2021-04-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0014_person_berthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='berthday',
            new_name='birthday',
        ),
    ]
