# Generated by Django 3.1.7 on 2021-04-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0015_auto_20210427_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nationalit',
            field=models.CharField(default='سورية', max_length=30),
        ),
    ]
