# Generated by Django 3.1.7 on 2021-05-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0017_person_father_die'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='motherln',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='person',
            name='card_number',
            field=models.PositiveIntegerField(default=0, null='True'),
        ),
        migrations.AlterField(
            model_name='person',
            name='count_child',
            field=models.PositiveIntegerField(default=0, null='True'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fhasbend',
            field=models.CharField(default=None, max_length=30, null='True'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(default='', max_length=20, null='True'),
        ),
        migrations.AlterField(
            model_name='person',
            name='hasbend',
            field=models.CharField(default='', max_length=30, null='True'),
        ),
        migrations.AlterField(
            model_name='person',
            name='percentage_health',
            field=models.PositiveIntegerField(default=0, null='True'),
        ),
        migrations.AlterField(
            model_name='person',
            name='place_birth',
            field=models.CharField(default=None, max_length=30, null='True'),
        ),
    ]
