# Generated by Django 3.1.7 on 2021-05-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0019_auto_20210504_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='nationalit',
            new_name='nationality',
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='amount_money',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='card_number',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='count_child',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='fhasbend',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='hasbend',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='motherln',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='person',
            name='place_birth',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
