# Generated by Django 3.1.7 on 2021-05-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0020_auto_20210505_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_place',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.SmallIntegerField(null=True),
        ),
    ]
