# Generated by Django 3.1.7 on 2021-06-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0027_auto_20210605_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('details', models.TextField(max_length=3000)),
                ('date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
